services:
  oxigate:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
      - "9090:9090"
    volumes:
      - ../config.yaml:/etc/oxigate/config.yaml:ro
    depends_on:
      - backend1
      - backend2
      - backend3

  backend1:
    image: nginx:alpine
    # simple static
  backend2:
    image: nginx:alpine
  backend3:
    image: nginx:alpine

  prometheus:
    image: prom/prometheus:v2.51.0
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9091:9090"
    depends_on:
      - oxigate

  grafana:
    image: grafana/grafana:10.4.0
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
